### ISSUE TITLE
Wrong MySQL query generated

### ISSUE THREAD

**Issue by shvaber** [DISID/gvnix#3] opened 2014-12-26 14:26 UTC
Good day team.
I created fresh project based on gvnix 1.4 version, it is based on MySQL database.
problem is that generated method in MVC controller 

    @RequestMapping(headers = "Accept=application/json", value = "/datatables/ajax", produces = "application/json")
    @ResponseBody
    public DatatablesResponse<Map<String, String>> findAllUsers(@DatatablesParams DatatablesCriterias criterias, @ModelAttribute User user, HttpServletRequest request)

contains 

SearchResults<User> searchResult = DatatablesUtils.findByCriteria (User.class, User.entityManager(), criterias, baseSearchValuesMap, conversionService_dtt, messageSource_dtt);

and it generates wrong query for mysql, like

Exception Message
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar(255)) LIKE '%12%' ESCAPE '!') OR CAST(last_login AS varchar(255)) LIKE '' at line 1 Error Code: 1064 Call: SELECT COUNT(uid) FROM user WHERE ((((LOWER(username) LIKE ? ESCAPE ? OR LOWER(email) LIKE ? ESCAPE ?) OR LOWER(name) LIKE ? ESCAPE ?) OR CAST(reg_date AS varchar(255)) LIKE ? ESCAPE ?) OR CAST(last_login AS varchar(255)) LIKE ? ESCAPE ?) bind => [%12%, !, %12%, !, %12%, !, %12%, !, %12%, !] 

Query: ReportQuery(referenceClass=User sql="SELECT COUNT(uid) FROM user WHERE ((((LOWER(username) LIKE ? ESCAPE ? OR LOWER(email) LIKE ? ESCAPE ?) OR LOWER(name) LIKE ? ESCAPE ?) OR CAST(reg_date AS varchar(255)) LIKE ? ESCAPE ?) OR CAST(last_login AS varchar(255)) LIKE ? ESCAPE ?)")

Exception Stack Trace
org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:377)
org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:260)
org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:516)
org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
com.mysema.query.jpa.impl.AbstractJPAQuery.count(AbstractJPAQuery.java:80)
org.gvnix.web.datatables.util.DatatablesUtils.findByCriteria(DatatablesUtils.java:975)
org.gvnix.web.datatables.util.DatatablesUtils.findByCriteria(DatatablesUtils.java:537)
org.gvnix.web.datatables.util.DatatablesUtils.findByCriteria(DatatablesUtils.java:416)
org.gvnix.web.datatables.util.DatatablesUtils.findByCriteria(DatatablesUtils.java:154)
uz.mediabay.web.mvc.UserController.findAllUsers(UserController.java:509)

Main problem is with CAST parts of the queries.

**Comment by eruiz** [comment] 2015-01-10 18:03
Hi, could you provide us the .roo file in order to reproduce the issue?

Thanks

**Comment by shvaber** [comment] 2015-03-04 09:26
I'm sorry that I left this request. Should I provide you more details, is this thread still active?

**Comment by eruiz** [comment] 2015-03-04 10:12
This thread is active but we cannot reproduce de error, so you should provide all the info that could help us to reproduce the issue: .roo file, db dump, etc.

**Comment by shvaber** [comment] 2015-03-04 11:01
here is whole .roo

// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-09 19:29:04
project --topLevelPackage uz.mediabay.web --projectName mediabay --java 6 --packaging JAR
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-09 19:29:04
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-09 19:29:15
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-09 19:32:54
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-09 19:33:17
persistence setup --provider ECLIPSELINK --database MYSQL 
jpa gvnix setup
// [failed] database reverse engineer --schema no-schema-required --package uz.mediabay.web.domain
osgi start --url file:///home/shvaber/.m2/repository/mysql/mysql-connector-java/5.1.18/mysql-connector-java-5.1.18.jar
database reverse engineer --schema no-schema-required --package uz.mediabay.web.domain
web mvc setup
web mvc all --package ~.web
web mvc jquery setup
web mvc jquery all
web mvc datatables setup
web mvc bootstrap setup
jpa batch all
web mvc batch setup
web mvc batch all
web mvc datatables all 
web mvc datatables all 
web report setup 
web mvc loupe setup
menu setup
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-09 20:49:30
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-10 11:43:06
hint
security setup
email sender setup --hostServer mail.mediabay.uz
web mvc datatables add --type ~.web.MediaController --ajax true --inline true
web mvc loupe set --controller  ~.web.MediaController 
web mvc loupe field --controller ~.web.MediaController --field user --caption username --max 5
web mvc loupe set --controller ~.mvc.MediaController
web mvc loupe field --controller ~.mvc.MediaController --field user --caption username --max 5
backup
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-10 15:53:30
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-10 15:53:49
hint
backup
web mvc loupe field --controller ~.mvc.MediaController --field genre
web mvc loupe field --controller ~.mvc.MediaController --field article --listPath articles --additionalFields "articleId,title" --max 5
web mvc loupe field --controller ~.mvc.MediaController --field article --additionalFields "articleId,title" --max 5
web mvc loupe field --controller ~.mvc.MediaController --field album --additionalFields "id,name" --max 5
logging setup --level INFO --package PROJECT 
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-10 20:24:30
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-10 20:24:47
hint
// [failed] web mvc loupe set --controller  ~.web.MediaController 
web mvc loupe set --controller  ~.mvc.MediaController 
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-10 20:40:00
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-11 10:01:21
hint
web mvc loupe field --controller ~.mvc.MediaController --field mediaType --additionalFields "tid,name"
web mvc loupe field --controller ~.mvc.MediaController --field holder --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.MediaController --field belongsTo --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.MediaController --field belongsTo --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.MediaController --field belongsTo
web mvc loupe field --controller ~.mvc.MediaController --field artists --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.MediaController --field language
web mvc loupe field --controller ~.mvc.MediaController --field vouchers4
backup
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-11 13:06:02
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2014-12-11 18:37:53
hint
backup
web mvc loupe field --controller ~.mvc.MediaController --field vouchers4
perform eclipse
backup
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-13 14:32:15
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-13 14:37:56
backup
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-13 14:45:59
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-13 14:46:07
web mvc controller --class ~.mvc.HomeController
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-13 20:38:29
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-15 15:30:32
// [failed] database reverse engineer --schema no-schema-required --package uz.mediabay.web.domain
osgi start --url file:///home/shvaber/.m2/repository/mysql/mysql-connector-java/5.1.18/mysql-connector-java-5.1.18.jar
database reverse engineer --schema no-schema-required --package uz.mediabay.web.domain
database reverse engineer --schema no-schema-required --package uz.mediabay.web.domain
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-15 20:34:38
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-16 11:00:08
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-16 15:26:06
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-19 19:34:03
web mvc loupe field --controller ~.mvc.AlbumController --field artist --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.AlbumController --field artist
web mvc loupe set --controller ~.mvc.AlbumController
web mvc loupe field --controller ~.mvc.AlbumController --field artist --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.AlbumController --field artist
web mvc loupe field --controller ~.mvc.AlbumController --field artist
web mvc loupe field --controller ~.mvc.AlbumController --field genre
web mvc loupe set --controller ~.mvc.AlbumController
web mvc loupe field --controller ~.mvc.AlbumController --field artist
// [failed] web mvc loupe set --controller ~.mvc.ChannelController
// [failed] web mvc loupe set --controller ~.mvc.ChannelController
// [failed] web mvc loupe set --controller ~.mvc.ChannelController
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-19 19:51:48
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-19 19:52:00
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-19 19:56:30
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-19 19:59:27
hint
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-19 20:01:47
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 12:17:08
web mvc loupe field --controller ~.mvc.AlbumController --field artist
web mvc loupe set --controller ~.mvc.AlbumController
web mvc loupe set --controller ~.mvc.ArticleController
web mvc loupe field --controller ~.mvc.ArticleController --field typeIp --additionalFields "tid,name" --caption Type
web mvc loupe field --controller ~.mvc.ArticleController --field typeId --additionalFields "tid,name" --caption Type
web mvc loupe field --controller ~.mvc.ArticleController --field typeId --additionalFields "tid,name"
web mvc loupe set --controller ~.mvc.AlbumController
web mvc loupe field --controller ~.mvc.AlbumController --field artist --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.ChannelThreadController --field channel --additionalFields "id,name"
web mvc loupe set --controller ~.mvc.ChannelController
web mvc loupe field --controller ~.mvc.ChannelController --field article --additionalFields "articleId,title"
web mvc loupe field --controller ~.mvc.ChannelController --field providerCountry --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.ChannelController --field providerCountry --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.ChannelController --field providerCountry --additionalFields "id,iso2"
database reverse engineer --schema no-schema-required --package uz.mediabay.web.domain
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 13:10:16
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 14:04:57
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 14:07:07
hint
hint
hint
backup
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 16:22:11
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 16:51:38
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 16:51:53
hint
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 17:05:09
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 17:05:17
hint
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 17:25:46
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 17:40:42
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 18:00:28
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 18:00:39
web mvc loupe set --controller ~.mvc.ChannelController
web mvc loupe field --controller ~.mvc.ChannelController --field providerCountry --additionalFields "id,name"
web mvc loupe field --controller ~.mvc.ChannelController --field providerCountry
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 18:07:28
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-20 18:09:04
web mvc loupe set --controller ~.mvc.ChannelThreadController
web mvc loupe field --controller ~.mvc.ChannelThreadController --field channel --additionalFields "nameJson"
web mvc loupe field --controller ~.mvc.ChannelThreadController --field channel --additionalFields "id"
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-20 20:01:12
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-22 14:58:45
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-22 20:35:02
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-25 16:38:39
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-25 18:16:45
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-25 19:47:25
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-25 20:35:31
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-26 12:00:00
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-26 13:16:01
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-29 15:05:37
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-29 17:30:55
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-29 17:31:15
hint
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-29 17:37:01
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2014-12-29 17:37:13
hint
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2014-12-29 20:28:27
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-07 10:57:21
hint
backup
database reverse engineer --schema no-schema-required --package uz.mediabay.web.domain
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-07 11:35:22
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-07 12:06:40
backup
// [failed] web mvc datatables all 
backup
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-07 20:08:37
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-13 20:18:04
backup
web mvc scaffold --backingType ~.domain.Paymer --class ~.mvc.PaymerController
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-13 20:35:30
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-14 11:54:27
hint
web mvc scaffold --backingType ~.domain.UserVoucher --class ~.mvc.UserVoucherController
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-14 18:38:15
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-14 18:38:33
hint
exit
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-14 19:23:15
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-15 12:38:45
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-15 20:26:45
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-16 16:49:42
backup
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-16 20:27:46
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-17 15:22:28
backup
backup
finder list --class ~.domain.Transfer --filter "Paymer"
finder list --class ~.domain.Transfer --filter "Paymer" --depth 2
finder list --class ~.domain.Transfer --filter "PaymerAnd" --depth 2
finder add --finderName findTransfersByPaymerAndDateCreatedBetween
// [failed] web mvc finder add --formBackingType ~.domain.Transfer --class ~.mvc.TransferController 
// [failed] web mvc finder add --formBackingType ~.domain.Transfer --class ~.mvc.TransferController 
// [failed] web mvc finder all
backup
// [failed] web mvc finder all
web mvc finder all
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-17 18:40:49
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log opened at 2015-01-17 19:01:42
backup
logging setup --level DEBUG --package ROOT 
// Spring Roo 1.2.4.RELEASE [rev 75337cf] log closed at 2015-01-17 19:43:39

Can't drop here sql dump file. Can you give me an email I will send dump to?

**Comment by jmvivo** [comment] 2015-03-04 12:54
I think this could be a problem of QueryDSL+ [ EclipseLink  or MySQL ] for the expression "CAST(last_login AS varchar(255))", check to disable "filterable" and "sortable" on List view for "lastLogin" property.

**Comment by jmvivo** [comment] 2015-03-17 15:25
We had performed some test and found that by using Hibernate the problems disappears, so this error seems to be a related to "cast a date to string" on Eclipselink (can be only over MySQL).

I close this issue as this problem can't be fixed on gvNIX.

**Closed by jmvivo** 2015-03-17 15:25 UTC
